dz6/core_hasker/urls.py
# -*- coding: utf-8 -*-
"""
Django url pattern class
"""

from django.urls import path

from dz6.core_hasker.views import QuestionListView, QuestionDetailView, \
    QuestionCreateView, QuestionSearchListView, AnswerCreateView, \
    QuestionVoteView, AnswerVoteView, error_404

urlpatterns = [path('', QuestionListView.as_view(),
                    name='question_list'),
               path('question/<slug:slug>', QuestionDetailView.as_view(),
                    name='question_detail'),
               path('new_question/', QuestionCreateView.as_view(),
                    name='new_question'),
               path('search/', QuestionSearchListView.as_view(),
                    name='question_search_list_view'),
               path('add_answer/<slug:slug>',
                    AnswerCreateView.as_view(), name='add_answer'),
               path('vote/question/<int:object_id>',
                    QuestionVoteView.as_view(), name='question_vote'),

               path('vote/answer/<int:object_id>',
                    AnswerVoteView.as_view(), name='answer_vote'),

               ]

handler404 = error_404

dz6/hasker/urls.py
"""hasker URL Configuration"""

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views, logout
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = \
    [
        path('admin/', admin.site.urls),
        path('accounts/login/', views.LoginView.as_view(
            redirect_authenticated_user=True,
            template_name="accounts/login.html"), name='login'),
        path('', include('core_hasker.urls')),
        path('accounts/', include('accounts.urls')),
        path('accounts/', include('django.contrib.auth.urls')),
        path('logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL},
             name='logout')

        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dz6/core_hasker/models.py
# -*- coding: utf-8 -*-
# pylint:disable=no-member
# pylint:disable=too-few-public-methods
"""
Django models
"""

import re

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone

from dz6.core_hasker.utils import pretty_date, unique_slugify


class Question(models.Model):
    """
    Class with fields for questions
    """
    title = models.CharField(max_length=140)
    slug = models.SlugField(max_length=255)
    question_tags = models.CharField(max_length=200)
    question_text = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)
    positive_votes = models.IntegerField(default=0)
    negative_votes = models.IntegerField(default=0)
    total_points = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title

    @property
    def get_trending(self):
        """
        Return ordered data by points
        """
        return self.order_by('-total_points', '-created_at')[:2]

    def get_date(self):
        """
        Get date in pretty format
        """
        return pretty_date(self.created_at)

    def get_tag_list(self):
        """
        Returns tag list for question
        """
        return re.split(" ", self.question_tags)

    def save(self, *args, **kwargs):
        """
        Saves question and updates votes
        """
        slug = self.title
        unique_slugify(self, slug)
        self.total_points = self.positive_votes - self.negative_votes
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """
        Returns absolute user URL
        """
        return reverse('question_detail', kwargs={'slug': self.slug})


class QuestionVote(models.Model):
    """
    Class for voteing on question
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    value = models.BooleanField(default=True)

    class Meta:
        """
        Django meta class
        """
        unique_together = ('user', 'question')


class Answer(models.Model):
    """
    Class for answer
    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)
    positive_votes = models.IntegerField(default=0)
    negative_votes = models.IntegerField(default=0)
    total_points = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        """
        Save answer method
        """
        self.total_points = self.positive_votes - self.negative_votes
        super().save(*args, **kwargs)

    def __unicode__(self):
        """
        Translate question to unicode
        """
        return f"id: {self.id} " \
               f"question: {self.question} " \
               f"text: {self.answer_text}"


class AnswerVote(models.Model):
    """
    Answer method for votes
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    value = models.BooleanField(default=True)

    class Meta:
        """
        Django meta class
        """
        unique_together = ('user', 'answer')

dz6/core_hasker/forms.py
# -*- coding: utf-8 -*-
# pylint:disable=too-few-public-methods
# pylint:disable=no-member
"""
Django forms module
"""
from django import forms

from .models import Question, Answer


class QuestionCreateForm(forms.ModelForm):
    """
    Form for create question and tags
    """

    class Meta:
        """
        Django meta class
        """
        model = Question
        fields = ['title', 'question_text', 'question_tags']

        labels = {
            'title': 'Title:',
            'question_text': 'Question detail:',
            }

    question_tags = forms.CharField(
        label='Tags:',
        widget=forms.TextInput(attrs={'Placeholder': 'tag1 tag2 tag3'}))

    def clean(self):
        """
        Clean data for user question form
        """
        tags = self.cleaned_data['question_tags']
        if len(tags.split()) > 3:
            raise forms.ValidationError('You cannot assign more than 3 tags')
        return self.cleaned_data


class AnswerCreateForm(forms.ModelForm):
    """
    Answer form for user creation
    """

    class Meta:
        """
        Django meta class
        """
        model = Answer
        fields = ['answer_text']

        labels = {'answer_text': '', }

    def __init__(self, author, current_question, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.author = author
        self.question = current_question

    def clean(self):
        """
        Clean data for user creation form
        """
        if Answer.object.filter(question=self.question, author=self.author):
            raise forms.ValidationError(
                'You were already asked')
        return self.cleaned_data

dz6/core_hasker/views.py
# -*- coding: utf-8 -*-
# pylint:disable=no-member
# pylint:disable=too-many-ancestors
# pylint:disable=too-many-branches
# pylint:disable=arguments-differ
"""
Views general file for Django
"""

import operator
from functools import reduce

from django.db.models import Q
from django.forms import ValidationError
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views.generic import ListView, DetailView, CreateView, View

from dz6.core_hasker.forms import AnswerCreateForm, QuestionCreateForm
from dz6.core_hasker.models import Question, QuestionVote, Answer, AnswerVote


def error_404(request):
    """
    Returns 404 error page
    """
    data = {}
    return render(request, '404.html', data)


class QuestionListView(ListView):
    """
    Question list view for web
    """
    context_object_name = 'question_list'
    model = Question
    paginate_by = 20

    def get_queryset(self):
        """
        Gets the queryset for questions based on total points
        """
        return Question.objects.all().order_by('-created_at', '-total_points')

    def get_template_names(self):
        """
        Returns template names
        """
        return 'core_hasker/question_list.html'


class QuestionSearchListView(QuestionListView):
    """
    Display a Question List page filtered by the search query.
    """
    paginate_by = 20

    def get_queryset(self):
        """
        Get queryset for search
        """
        result = super().get_queryset()

        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            if query.startswith('tag:'):
                result = result.filter(
                    reduce(operator.and_,
                           (Q(question_tags__icontains=q[4:])
                            for q in query_list))
                    )
            else:
                result = result.filter(
                    reduce(operator.and_,
                           (Q(title__icontains=q) for q in query_list)) |
                    reduce(operator.and_,
                           (Q(question_text__icontains=q) for q in query_list))
                    )

        return result.order_by('-created_at')

    def get_template_names(self):
        """
        Gets template for question list
        """
        return 'core_hasker/question_list.html'


class QuestionDetailView(DetailView):
    """
    Detailed view for question
    """
    model = Question
    context_object_name = 'question_detail'
    template_name = 'core_hasker/question_detail.html'

    def get_context_data(self, **kwargs):
        """
        Gets context data for question details
        """
        context = super().get_context_data(**kwargs)
        selected_question = get_object_or_404(
            Question, slug=self.kwargs['slug'])
        context['form'] = AnswerCreateForm(self, self.request.user,
                                           instance=selected_question)
        return context


class QuestionCreateView(CreateView):
    """
    View for create question page
    """
    form_class = QuestionCreateForm
    template_name = 'core_hasker/new_question.html'
    context_object_name = 'new_question_form'

    def form_valid(self, form):
        """
        Check if question is valid
        """
        new_question = form.save(commit=False)
        new_question.author = self.request.user
        new_question.created_at = timezone.now()
        new_question.save()
        return HttpResponseRedirect(
            reverse('question_detail', kwargs={'slug': new_question.slug}))


class QuestionVoteView(View):
    """
    View for question vote page
    """
    model = Question
    vote_model = QuestionVote

    def post(self, request, object_id):
        """
        Post method for adding question
        """
        vote_target = get_object_or_404(self.model, pk=object_id)
        if vote_target.author == request.user:
            raise ValidationError(
                'Sorry, voting for your own question is not possible.')

        upvote = request.POST.get('upvote', None) is not None
        vote, created = self.vote_model.objects.get_or_create(
            defaults={'value': upvote},
            user=request.user,
            question=vote_target)
        if created:
            if upvote:
                vote_target.positive_votes += 1
            else:
                vote_target.negative_votes += 1

        else:
            if vote.value == upvote:
                vote.delete()

                if upvote:
                    vote_target.positive_votes -= 1

                else:
                    vote_target.negative_votes -= 1

            else:
                vote.value = upvote
                vote.save()
                if upvote:
                    vote_target.positive_votes += 1
                    vote_target.negative_votes -= 1

                else:
                    vote_target.negative_votes += 1
                    vote_target.positive_votes -= 1

        vote_target.save()

        next_url = request.POST.get('next', '')
        if next_url:
            return redirect(next_url)

        return HttpResponseRedirect(
            reverse('question_detail', kwargs={'slug': vote_target.slug}))


class AnswerVoteView(View):
    """
    View for answers page
    """
    model = Answer
    vote_model = AnswerVote

    def post(self, request, object_id):
        """
        Post method for answer page
        """
        vote_target = get_object_or_404(self.model, pk=object_id)
        if vote_target.author == request.user:
            raise ValidationError(
                'Sorry, voting for your own answer is not possible.')

        upvote = request.POST.get('upvote', None) is not None
        vote, created = self.vote_model.objects.get_or_create(
            defaults={'value': upvote},
            user=request.user,
            answer=vote_target)
        if created:
            if upvote:
                vote_target.positive_votes += 1
            else:
                vote_target.negative_votes += 1

        else:
            if vote.value == upvote:
                vote.delete()
                if upvote:
                    vote_target.positive_votes -= 1
                else:
                    vote_target.negative_votes -= 1

            else:
                vote.value = upvote
                vote.save()
                if upvote:
                    vote_target.positive_votes += 1
                    vote_target.negative_votes -= 1
                else:
                    vote_target.negative_votes += 1
                    vote_target.positive_votes -= 1

            vote_target.save()

        next_url = request.POST.get('next', '')
        if next_url:
            return redirect(next_url)
        return HttpResponseRedirect(
            reverse('question_detail',
                    kwargs={'slug': vote_target.question.slug}))


class AnswerCreateView(CreateView):
    """
    View for creating anserts
    """
    form_class = AnswerCreateForm
    template_name = 'core_hasker/question_detail.html'

    def get_form(self):
        """
        Get form for answer creation
        """
        current_question = get_object_or_404(Question,
                                             slug=self.kwargs['slug'])
        form = AnswerCreateForm(self.request.user, current_question,
                                self.request.POST)
        return form

    def get_context_data(self, **kwargs):
        """
        Gets context data for view creation
        """
        context = super().get_context_data(**kwargs)
        current_question = get_object_or_404(Question,
                                             slug=self.kwargs['slug'])
        answer_form = self.get_form()
        context['question_detail'] = current_question
        context['form'] = answer_form
        return context

    def form_valid(self, form):
        """
        Check if data input is valid
        """
        current_question = get_object_or_404(Question,
                                             slug=self.kwargs['slug'])
        instance = form.save(commit=False)
        instance.question = current_question
        instance.author = self.request.user
        instance.save()
        return HttpResponseRedirect(
            reverse('question_detail', kwargs={'slug': current_question.slug}))

dz6/templates/core_hasker/new_question.html
{% extends "base.html" %}

{% block subtitle %} New Question {% endblock %}

{% load widget_tweaks %}

{% block main %}

<form id="question-form" action="" onsubmit="editor.post();" method="post">
    {% csrf_token %}

    {% for hidden in form.hidden_fields %}
      {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}

      <div class="form-group">
        <label>{{ field.label }}</label>
        {{ field|add_class:'form-control' }}
        {% for error in field.errors %}
          <span class="help-block">{{ error }}</span>
        {% endfor %}
      </div>
    {% endfor %}

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}



    <div class="form-group">
      <button type="submit" class="btn btn-success">
        <span class="glyphicon glyphicon-ok"></span> Save
      </button>
      <a href="{% url 'question_list' %}" class="btn btn-default">Cancel</a>
    </div>


</form>
{% endblock %}

dz6/templates/core_hasker/question_detail.html
{% extends "base.html" %}
{% block subtitle %}Question detail{% endblock %}
{% load static %}
{% load widget_tweaks %}

{% block main %}


<div class="row">
    <div class="col-lg-2">

        {% if user.is_authenticated and user != question_detail.author %}
        <form action="{% url 'question_vote' question_detail.id %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="upvote" value="on">
          <input type="hidden" name="next" value="{{ request.path }}">
          <input type="image" type="submit" src = "{% static 'site_img/vote-up-off.png' %}" title="Vote this question UP. (click again to undo)"></button>
        </form>
        {% else %}
        <br>
        <br>
        {% endif %}
        <h3 style="color:#808080"><a class="invisible">..</a><span>{{question_detail.total_points}}</span></h3>

        {% if user.is_authenticated and user != question_detail.author %}
        <form action="{% url 'question_vote' question_detail.id %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ request.path }}">
          <input type="image" type="submit" src = "{% static 'site_img/vote-down-off.png' %}"button type="submit"  data-placement="bottom" title="Vote this question DOWN if it is innapropriate or incorrect. (click again to undo)"></button>
        </form>
        {% endif %}
    </div>

    <div class="col-lg-10">
        <br>
        <h4>
            <a class="text-dark">
                {{ question_detail.title }}
                <br>
            </a>
        </h4>
        <p>{{question_detail.question_text}}</p>
    </div>
</div>
<div class="row">
    <div class="col-lg-2">
    </div>
    <div class="col-lg-5">
        Tags:
          {% for tag in question_detail.get_tag_list %}
            <a href="{% url 'question_search_list_view' %}?q=tag:{{ tag }}" style="background-color: peachpuff">
                {{ tag }}
            </a>{% if not forloop.last %}, {% endif %}
          {% endfor %}
    </div>
    <div class="col-lg-5" align="right">
        <img src="{{question_detail.author.avatar.url}}" height="40">
        <a class="invisible">...</a>
        <a>{{question_detail.author.login}}</a>
        <a class="invisible">........</a>
    </div>

</div>
<div class="row">
    <div class="col-lg-12">
        <hr>
    </div>
</div>


{% for answer in question_detail.answer_set.all|dictsortreversed:'total_points'|dictsortreversed:'created_at' %}
<div class="row">
    <div class="col-lg-2">
        {% if user.is_authenticated and user != answer.author %}
        <form action="{% url 'answer_vote' answer.id %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ request.path }}">
          <input type="hidden" name="upvote" value="on">
          <input type="image" type="submit" src = "{% static 'site_img/vote-up-off.png' %}" title="Vote this answer UP. (click again to undo)"></button>
        </form>
        {% else %}
        <br>
        <br>
        {% endif %}
        <h3 style="color:#808080"><a class="invisible">..</a><span>{{answer.total_points}}</span></h3>

        {% if user.is_authenticated and user != answer.author %}
        <form action="{% url 'answer_vote' answer.id %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ request.path }}">
          <input type="image" type="submit" src = "{% static 'site_img/vote-down-off.png' %}"button type="submit"  data-placement="bottom" title="Vote this answer DOWN if it is innapropriate or incorrect. (click again to undo)"></button>
        </form>
        {% endif %}
    </div>

    <div class="col-lg-10">
        <br>
        <p>{{answer.answer_text}}</p>
    </div>
</div>

<div class="row">
    <div class="col-lg-2">
    </div>
    <div class="col-lg-5">
    </div>
    <div class="col-lg-5" align="right">
        <img src="{{answer.author.avatar.url}}" height="40">
        <a class="invisible">...</a>
        <a>{{answer.author.login}}</a>
        <a class="invisible">........</a>
    </div>

</div>

<div class="row">
    <div class="col-lg-12">
        <hr>
    </div>
</div>

{% endfor %}

{% if user.is_authenticated %}
<div class="row">
    <div class="col-lg-2"> </div>

    <div class="col-lg-10">

    <h3>Your answer:</h3>

        <form id="answer-form" action="{% url 'add_answer' slug=question_detail.slug %}" onsubmit="editor.post();" method="POST">
           {% csrf_token %}

        {% for hidden in form.hidden_fields %}
          {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control' }}
            {% for error in field.errors %}
              <span class="help-block">{{ error }}</span>
            {% endfor %}
          </div>
        {% endfor %}

        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}



        <div class="form-group">
          <button type="submit" class="btn btn-success">
            <span class="glyphicon glyphicon-ok"></span> Add Answer
          </button>
        </div>
        </form>
    </div>
</div>
{% endif %}

{% endblock %}

dz6/templates/core_hasker/question_list.html
{% extends "base.html" %}

{% block main %}
{% for question in question_list  %}
<div class="row">
    <div class="col-lg-12">
        <hr>
    </div>
</div>
<div class="row">
    <div class="col-lg-3">

        <div class="row">
            <div class="col-lg-6">
                <div class="well">
                    <div class="col text-center">
                    {{question.total_points}}
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="well">
                    <div class="col text-center">
                        {{question.answer_set.count}}
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="well">
                    <div class="col text-center">
                        Votes
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="well">
                    Answers
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <h6>
            <a class="text-dark" href="{{ question.get_absolute_url }}" >
                {{ question.title }}
            </a>
        </h6>
        Tags:
          {% for tag in question.get_tag_list %}
            <a href="{% url 'question_search_list_view' %}?q=tag:{{ tag }}" style="background-color: peachpuff">
                {{ tag }}
            </a>
            {% if not forloop.last %}, {% endif %}
          {% endfor %}

    </div>
    <div class="col-lg-3">
        <div class="row">
            <div class="col text-center">
                    <a class="mx-auto">
                        {{question.author}}
                    </a>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="well">
                    asked: {{ question.get_date }}
                </div>
            </div>
        </div>
    </div>

</div>

    {% empty %}
      <div class="alert alert-info text-center">
          No questions here :(
      </div>
{% endfor %}

<div class="row">
    <div class="col-lg-12">
        <hr>
    </div>
</div>

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">&laquo;</a>
      </li>
    {% else %}
      <li class="disabled">
          <a class="page-link" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
          </a>
      </li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active">
            <a class="page-link" aria-label="Previous">
                <span>{{ i }}
                    <span class="sr-only">(current)</span>
                </span>
            </a>
        </li>
      {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
      </li>
    {% else %}
      <li class="disabled">
          <a class="page-link" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
          </a>
      </li>
    {% endif %}
  </ul>
{% endif %}

{% endblock %}